inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'tmp/*'
    - Gemfile
    - Rakefile

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
